CREATE DATABASE alpha_dev;
USE alpha_dev;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    `key` VARCHAR(255) UNIQUE NOT NULL,
    device_id VARCHAR(255) UNIQUE DEFAULT NULL,
    expires_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
